### ISSUE TITLE
Publish to Central Repository

### ISSUE THREAD

**Issue by altus34** [Xray-App/xray-junit-extensions#12]
Hello,
 
Is it possible to publish it on maven central ?
Many organizations use a Nexus or  an Artifactory as proxy to external repositories.
So if you don't publish it on maven central, have you a recipe to create a proxy of your GitHub maven packages registry into Nexus or Artifactory?

Regards.

**Comment by bitcoder** [comment]
Hi @altus34 , it's not on my plans on the short term but something to consider. It's just a matter of effoer; whenever I looked at it it didnt seem straightforward. 
Cant you access gh packages? 
On the recipe you mentioned, I don't have nothing  sorry.

**Comment by bitcoder** [comment]
For reference:

- https://maven.apache.org/repository/guide-central-repository-upload.html
- https://central.sonatype.org/publish/publish-guide/
- https://central.sonatype.org/publish/requirements/

**Comment by altus34** [comment]
Hi @bitcoder,

I know the process I personally publish in maven central.
It's not  straightforward but it not complicated (quality require gates)

After it depend of the type of users you want to target.
As I can see you are a product for enterprise and your users are enterprises users (like me with my company).

So for the moment we are unable to use it in our company.
Good change with your other clients/users.

Regards

**Comment by Alje001** [comment]
Hi @bitcoder, I would like to ask you whether you had a look on this. Because I would like to use this library in our junit tests and integrate the tests with in jira Xray.
To do that we prefer using gradle with maven repository.

thank you for supporting.

best regards

**Comment by bitcoder** [comment]
Hi @Alje001 , unfortunately not yet. It's on my to dos but no ETA for it as I have other things going in the short/mid term. It's not forgotten though

**Comment by bitcoder** [comment]
pending adding TXT record on DNS and further validations

**Comment by bitcoder** [comment]
Will be available on https://central.sonatype.org/

Additional refs:

- https://github.com/simpligility/ossrh-demo/blob/master/pom.xml

**Comment by altus34** [comment]
Great job :+1: 
Thank you so much.

**Comment by Alje001** [comment]
@bitcoder thank you for hour effort. I will try it soon.
Best regards

**Comment by bitcoder** [comment]
Thanks!
Anything please let me know.
I had some  enhancements to make that I only finished now. I think it is being propagated to the main central repository right now

**Comment by rfelgent** [comment]
hi @bitcoder , the version 0.0.7 is not published.
