### ISSUE TITLE
Incomplete junit report when setting surefire.rerunFailingTestsCount parameter

### ISSUE THREAD

**Issue by ZescherW** [Xray-App/xray-junit-extensions#20]
I have a project with some flaky tests. So when I set `surefire.rerunFailingTestsCount=2` in order to re-run the flaky tests, `xray-junit-extensions` plugin generates a junit report including only flaky tests (omitting all the other tests that weren't re-run).

~~The generated (incomplete) junit report is used as input for `xray-maven-plugin`, so using `add_timestamp_to_report_filename=true` won't be a valid workaround as mentioned in https://github.com/Xray-App/xray-junit-extensions/issues/11~~

Editing this once again. I just realised that it's possible to import results from a folder: https://github.com/Xray-App/xray-maven-plugin#configurations-for-importing-test-results

Closing this issue then.

**Comment by amard33p** [comment]
>I just realised that it's possible to import results from a folder:

@ZescherW I believe you are referring to `target/surefire-reports/` folder here. But does the xray importer have the intelligence to identify that it needs to import a test's rerun result and not the original result?

I could not find any references to the surefire tags `rerunFailure`, `flakyFailure` in the codebase.

**Comment by bitcoder** [comment]
As I mentioned, please report the issue/doubt on the respective project; not here please.
