### ISSUE TITLE
Can the extension also produce Open Test Report XML file?

### ISSUE THREAD

**Issue by performrumpf** [Xray-App/xray-junit-extensions#25]
As a Java developer using JUnit 5 I struggled a lot with the missing support of data-driven test results in legacy XML reporting. I tried to compensate that with an own TestExecutionListener generating single-page report files.

This was unless I heard of the introduction of [Open Test Reporting](https://junit.org/junit5/docs/current/user-guide/#junit-platform-reporting-open-test-reporting) since the release of [JUnit 5.9](https://junit.org/junit5/docs/current/release-notes/index.html#release-notes-5.9.0).

Can your extension also create such report files, or is there any plan that such report files can be imported to Jira XRay?

**Comment by bitcoder** [comment]
Hi, Xray doesn't support yet that format as of Dec2022. I would recommend to [reach out to Xray support directly](https://jira.getxray.app/servicedesk/customer/portal/2) and ask for an improvement so the team can analyze it.
In my perspective, only after Xray supports it,  we can then see if it would make sense what to do from this project side.
AFAIK, the Open Test Reporting is not yet used that much... but I may be wrong. Need some time to analyze this. Feedback is welcome.

**Comment by bitcoder** [comment]
I will close this as the question has been answered. Thanks
