### ISSUE TITLE
Sett Fix version on the Text Execution Key and Create a Test plan 

### ISSUE THREAD

**Issue by InduKrish** [Xray-App/xray-junit-extensions#26]
To produce better reporting in JIRA, we would like to add a fix version every time a new text execution is created.

We found your plugin helpful and run our project using it, and would like to clarify if there is a way to update a fix version on the text execution everytime the test runs in the pipeline.
and also would like to create a Test plan .

Is there a way to automatically create the test plan using the plugin?

Currently we are using @Requirement and @XrayTest tags , Please advise how i can have a fix version added to all the test executions and if there is a way to automatically create the test plan and associate all test executions to the test plan? Thank you!

@Test
    @Requirement({"BECB-329", "BECB-220", "BECB-274"})
    @XrayTest(key = "BEXP-73")
    @DisplayName("Validate bases end points ")
    public void test105_crewBasesCrewInFlight() {
        
    }

**Comment by bitcoder** [comment]
Hi, 
the fixversion and other information such as the Test Plan key, is not stored on the JUnit XML report.
That information is passed whenever submiting the report file, i.e., on the HTTP REST api call as seen on this example: https://docs.getxray.app/display/XRAY/Import+Execution+Results+-+REST#ImportExecutionResultsREST-JUnitXMLresults

So, it's out of scope of this plugin.

**Comment by InduKrish** [comment]
just to make that i understand correctly.
Are you advising that i should be using the Junit xml report that the Xray plugin produces and use the following api and query params?

This is the command we currently use:
`XRAY_COMMAND: 'curl -H "Content-Type: multipart/form-data" -u $JIRA_USER:$JIRA_PASSWORD -F "file=@test-functional/target/${XRAY_REPORT}" "$JIRA_SERVER_URL_PROD/rest/raven/1.0/import/execution/junit?projectKey=BDXP"'`

These are the annotations i currently use. this will automatically create test executions and map all the tests to all the requirements mentioned below, ie BACB-329", "BACB-220", "BACB-274.
    @Test
    @Requirement({"BACB-329", "BACB-220", "BACB-274"})
    @XrayTest(key = "BDXP-73")
    @DisplayName("Validate crew.")

Like i mentioned above, now i would like to update fix version nos' in all the text executions that are automatically created and all the tests to the test plan..

 POST /rest/raven/1.0/import/execution/junit -->Should I pass Test Plan and fix version as a query params and submit the same JUNIT xml that the Xray plugin produces? Will the api add the fix revision number to all test executions that xray plugin automatically creates in JIRA and all the Xary tests to the test plan id that i pass as a query param?

Can you please confirm?
**curl -H "Content-Type: multipart/form-data" -u admin:admin -F "file=@report.xml" http://yourserver/rest/raven/1.0/import/execution/junit?projectKey=XTP&testPlanKey=XTP-12&revision=v2.1.0**

<img width="1400" alt="Screen Shot 2023-01-28 at 10 25 06 PM" src="https://user-images.githubusercontent.com/113629123/215304844-6d5f486c-7f48-41ae-8e3f-54e0bc6611a0.png">


<img width="1400" alt="Screen Shot 2023-01-28 at 10 24 59 PM" src="https://user-images.githubusercontent.com/113629123/215304847-e4e3c4b1-e0da-421e-ae59-ee05085a3886.png">

**Comment by bitcoder** [comment]
Yes exactly.
You need to pass those attributes not on the report itself but on the API call as query parameters.
It will create a Test Execution issues with the given fixversion, the given revision, and the given testplan.

**Comment by bitcoder** [comment]
I'll close this ticket as this is out-of-scope of this extension
