### ISSUE TITLE
Xray Plugin: when we use Xray plugin in Serenity framework, Xray listener suppresses any exception that test shows and marking the build successful although there are exceptions in the test.

### ISSUE THREAD

**Issue by InduKrish** [Xray-App/xray-junit-extensions#27]
when we use Xray plugin in Serenity framework, Xray listener suppresses any exception that test shows and marking the build successful.

We observed that the xary plugin suppresses any exception that the test throws and producing inconsistent build status when we run the tests using Serenity -junit 5 framework and using Xray-junit5 plugin to produce an xml for xray reporting..

although there were exceptions in the code in Serenity -junit 5 framework, the test build was marked successful, and after removing the xray listener, we noticed that the serenity-junit 5 marked the build failed whenever there are exception in the build as expected.

Can you please advise why Xray listener is causing the build status to be not appropriate?, when used in Serenity framework.

**Listener**

org.junit.platform.launcher.TestExecutionListener
app.getxray.xray.junit.customjunitxml.EnhancedLegacyXmlReportGeneratingListener

**build.gradle**
Serenity-junit5

testImplementation 'net.serenity-bdd:serenity-core'
testImplementation 'net.serenity-bdd:serenity-junit5'
testImplementation 'net.serenity-bdd:serenity-rest-assured'
testImplementation 'org.junit.jupiter:junit-jupiter-api'
testImplementation 'org.junit.platform:junit-platform-suite-engine'
testImplementation 'app.getxray:xray-junit-extensions'

**Comment by bitcoder** [comment]
I'm not a frequent Serenity user  so to be able to help I need help from someone else most probably.
Nevertheless, it would help if you could create a full working example, for example on GitHb repo, that could show this behavior and thus be able to replicate it as the information you provided is very scarce.

**Comment by bitcoder** [comment]
Closing this for lack of feedback
